// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2_AR71275_op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module digitrec_kernel_update (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp_0_address0,
        temp_0_ce0,
        temp_0_q0,
        temp_1_address0,
        temp_1_ce0,
        temp_1_q0,
        temp_2_address0,
        temp_2_ce0,
        temp_2_q0,
        temp_3_address0,
        temp_3_ce0,
        temp_3_q0,
        temp_4_address0,
        temp_4_ce0,
        temp_4_q0,
        temp_5_address0,
        temp_5_ce0,
        temp_5_q0,
        temp_6_address0,
        temp_6_ce0,
        temp_6_q0,
        temp_7_address0,
        temp_7_ce0,
        temp_7_q0,
        knn_mat_0_0_read,
        knn_mat_0_1_read,
        knn_mat_0_2_read,
        knn_mat_0_3_read,
        knn_mat_1_0_read,
        knn_mat_1_1_read,
        knn_mat_1_2_read,
        knn_mat_1_3_read,
        knn_mat_2_0_read,
        knn_mat_2_1_read,
        knn_mat_2_2_read,
        knn_mat_2_3_read,
        knn_mat_3_0_read,
        knn_mat_3_1_read,
        knn_mat_3_2_read,
        knn_mat_3_3_read,
        knn_mat_4_0_read,
        knn_mat_4_1_read,
        knn_mat_4_2_read,
        knn_mat_4_3_read,
        knn_mat_5_0_read,
        knn_mat_5_1_read,
        knn_mat_5_2_read,
        knn_mat_5_3_read,
        knn_mat_6_0_read,
        knn_mat_6_1_read,
        knn_mat_6_2_read,
        knn_mat_7_0_read,
        knn_mat_7_1_read,
        knn_mat_7_2_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] temp_0_address0;
output   temp_0_ce0;
input  [63:0] temp_0_q0;
output  [7:0] temp_1_address0;
output   temp_1_ce0;
input  [63:0] temp_1_q0;
output  [7:0] temp_2_address0;
output   temp_2_ce0;
input  [63:0] temp_2_q0;
output  [7:0] temp_3_address0;
output   temp_3_ce0;
input  [63:0] temp_3_q0;
output  [7:0] temp_4_address0;
output   temp_4_ce0;
input  [63:0] temp_4_q0;
output  [7:0] temp_5_address0;
output   temp_5_ce0;
input  [63:0] temp_5_q0;
output  [7:0] temp_6_address0;
output   temp_6_ce0;
input  [63:0] temp_6_q0;
output  [7:0] temp_7_address0;
output   temp_7_ce0;
input  [63:0] temp_7_q0;
input  [7:0] knn_mat_0_0_read;
input  [7:0] knn_mat_0_1_read;
input  [7:0] knn_mat_0_2_read;
input  [7:0] knn_mat_0_3_read;
input  [7:0] knn_mat_1_0_read;
input  [7:0] knn_mat_1_1_read;
input  [7:0] knn_mat_1_2_read;
input  [7:0] knn_mat_1_3_read;
input  [7:0] knn_mat_2_0_read;
input  [7:0] knn_mat_2_1_read;
input  [7:0] knn_mat_2_2_read;
input  [7:0] knn_mat_2_3_read;
input  [7:0] knn_mat_3_0_read;
input  [7:0] knn_mat_3_1_read;
input  [7:0] knn_mat_3_2_read;
input  [7:0] knn_mat_3_3_read;
input  [7:0] knn_mat_4_0_read;
input  [7:0] knn_mat_4_1_read;
input  [7:0] knn_mat_4_2_read;
input  [7:0] knn_mat_4_3_read;
input  [7:0] knn_mat_5_0_read;
input  [7:0] knn_mat_5_1_read;
input  [7:0] knn_mat_5_2_read;
input  [7:0] knn_mat_5_3_read;
input  [7:0] knn_mat_6_0_read;
input  [7:0] knn_mat_6_1_read;
input  [7:0] knn_mat_6_2_read;
input  [7:0] knn_mat_7_0_read;
input  [7:0] knn_mat_7_1_read;
input  [7:0] knn_mat_7_2_read;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;
output  [7:0] ap_return_16;
output  [7:0] ap_return_17;
output  [7:0] ap_return_18;
output  [7:0] ap_return_19;
output  [7:0] ap_return_20;
output  [7:0] ap_return_21;
output  [7:0] ap_return_22;
output  [7:0] ap_return_23;
output  [7:0] ap_return_24;
output  [7:0] ap_return_25;
output  [7:0] ap_return_26;
output  [7:0] ap_return_27;
output  [7:0] ap_return_28;
output  [7:0] ap_return_29;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg temp_0_ce0;
reg temp_1_ce0;
reg temp_2_ce0;
reg temp_3_ce0;
reg temp_4_ce0;
reg temp_5_ce0;
reg temp_6_ce0;
reg temp_7_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [10:0] y3_1_fu_974_p2;
reg   [10:0] y3_1_reg_2302;
wire    ap_CS_fsm_state2;
wire   [1:0] i1_1_fu_1166_p2;
reg   [1:0] i1_1_reg_2310;
wire    ap_CS_fsm_state3;
wire   [7:0] grp_fu_710_p5;
wire   [0:0] exitcond_fu_1160_p2;
wire   [2:0] tmp_24_fu_1172_p1;
wire   [7:0] grp_fu_722_p6;
wire   [7:0] grp_fu_736_p6;
wire   [7:0] grp_fu_750_p6;
wire   [7:0] grp_fu_764_p6;
wire   [7:0] grp_fu_778_p6;
wire   [7:0] grp_fu_792_p6;
wire   [7:0] grp_fu_806_p5;
wire   [2:0] tmp_12_fu_1176_p1;
reg   [2:0] tmp_12_reg_2358;
wire   [63:0] p_max_id_fu_1226_p3;
wire    ap_CS_fsm_state4;
reg   [10:0] y3_reg_552;
wire    ap_CS_fsm_state5;
wire   [63:0] ap_phi_mux_max_id_phi_fu_568_p4;
reg   [63:0] max_id_reg_564;
wire   [0:0] exitcond1_fu_968_p2;
reg   [1:0] i1_reg_576;
reg   [7:0] knn_mat_load_1_0_phi_reg_588;
wire   [63:0] newIndex1_fu_1190_p1;
reg   [7:0] knn_mat_7_2_fu_148;
wire   [7:0] knn_mat_7_2_3_fu_2002_p6;
wire   [0:0] tmp_11_fu_1389_p2;
wire   [2:0] tmp_23_fu_1259_p1;
reg   [7:0] knn_mat_7_1_fu_152;
wire   [7:0] knn_mat_7_1_3_fu_2016_p6;
reg   [7:0] knn_mat_7_0_fu_156;
wire   [7:0] knn_mat_7_0_3_fu_2030_p6;
reg   [7:0] knn_mat_6_2_fu_160;
wire   [7:0] knn_mat_6_2_3_fu_1408_p6;
reg   [7:0] knn_mat_6_1_fu_164;
wire   [7:0] knn_mat_6_1_3_fu_1422_p6;
reg   [7:0] knn_mat_6_0_fu_168;
wire   [7:0] knn_mat_6_0_3_fu_1436_p6;
reg   [7:0] knn_mat_5_3_fu_172;
wire   [7:0] knn_mat_5_3_3_fu_1477_p6;
reg   [7:0] knn_mat_5_2_fu_176;
wire   [7:0] knn_mat_5_2_3_fu_1491_p6;
reg   [7:0] knn_mat_5_1_fu_180;
wire   [7:0] knn_mat_5_1_3_fu_1505_p6;
reg   [7:0] knn_mat_5_0_fu_184;
wire   [7:0] knn_mat_5_0_3_fu_1519_p6;
reg   [7:0] knn_mat_4_3_fu_188;
wire   [7:0] knn_mat_4_3_3_fu_1565_p6;
reg   [7:0] knn_mat_4_2_fu_192;
wire   [7:0] knn_mat_4_2_3_fu_1579_p6;
reg   [7:0] knn_mat_4_1_fu_196;
wire   [7:0] knn_mat_4_1_3_fu_1593_p6;
reg   [7:0] knn_mat_4_0_fu_200;
wire   [7:0] knn_mat_4_0_3_fu_1607_p6;
reg   [7:0] knn_mat_3_3_fu_204;
wire   [7:0] knn_mat_3_3_3_fu_1653_p6;
reg   [7:0] knn_mat_3_2_fu_208;
wire   [7:0] knn_mat_3_2_3_fu_1667_p6;
reg   [7:0] knn_mat_3_1_fu_212;
wire   [7:0] knn_mat_3_1_3_fu_1681_p6;
reg   [7:0] knn_mat_3_0_fu_216;
wire   [7:0] knn_mat_3_0_3_fu_1695_p6;
reg   [7:0] knn_mat_2_3_fu_220;
wire   [7:0] knn_mat_2_3_3_fu_1741_p6;
reg   [7:0] knn_mat_2_2_fu_224;
wire   [7:0] knn_mat_2_2_3_fu_1755_p6;
reg   [7:0] knn_mat_2_1_fu_228;
wire   [7:0] knn_mat_2_1_3_fu_1769_p6;
reg   [7:0] knn_mat_2_0_fu_232;
wire   [7:0] knn_mat_2_0_3_fu_1783_p6;
reg   [7:0] knn_mat_1_3_fu_236;
wire   [7:0] knn_mat_1_3_3_fu_1829_p6;
reg   [7:0] knn_mat_1_2_fu_240;
wire   [7:0] knn_mat_1_2_3_fu_1843_p6;
reg   [7:0] knn_mat_1_1_fu_244;
wire   [7:0] knn_mat_1_1_3_fu_1857_p6;
reg   [7:0] knn_mat_1_0_fu_248;
wire   [7:0] knn_mat_1_0_3_fu_1871_p6;
reg   [7:0] knn_mat_0_3_fu_252;
wire   [7:0] knn_mat_0_3_3_fu_1917_p6;
reg   [7:0] knn_mat_0_2_fu_256;
wire   [7:0] knn_mat_0_2_3_fu_1931_p6;
reg   [7:0] knn_mat_0_1_fu_260;
wire   [7:0] knn_mat_0_1_3_fu_1945_p6;
reg   [7:0] knn_mat_0_0_fu_264;
wire   [7:0] knn_mat_0_0_3_fu_1959_p6;
reg   [63:0] grp_fu_699_p1;
wire   [1:0] grp_fu_710_p4;
wire   [1:0] grp_fu_722_p5;
wire   [1:0] grp_fu_736_p5;
wire   [1:0] grp_fu_750_p5;
wire   [1:0] grp_fu_764_p5;
wire   [1:0] grp_fu_778_p5;
wire   [1:0] grp_fu_792_p5;
wire   [1:0] grp_fu_806_p4;
wire   [7:0] newIndex_fu_1180_p4;
wire   [7:0] knn_mat_load_2_0_phi_fu_1206_p6;
wire   [0:0] tmp_22_fu_1220_p2;
wire   [63:0] tmp_21_fu_1202_p1;
wire   [31:0] tmp_2_fu_1237_p9;
wire   [0:0] sel_tmp3_fu_1299_p2;
wire   [0:0] sel_tmp1_fu_1293_p2;
wire   [0:0] sel_tmp8_fu_1287_p2;
wire   [0:0] sel_tmp6_fu_1281_p2;
wire   [0:0] sel_tmp4_fu_1275_p2;
wire   [0:0] sel_tmp2_fu_1269_p2;
wire   [0:0] sel_tmp_fu_1263_p2;
wire   [0:0] or_cond_fu_1313_p2;
wire   [7:0] newSel_fu_1305_p3;
wire   [7:0] newSel1_fu_1319_p3;
wire   [0:0] or_cond1_fu_1327_p2;
wire   [0:0] or_cond2_fu_1341_p2;
wire   [7:0] newSel2_fu_1333_p3;
wire   [7:0] newSel3_fu_1347_p3;
wire   [0:0] or_cond3_fu_1363_p2;
wire   [7:0] newSel4_fu_1355_p3;
wire   [7:0] newSel5_fu_1369_p3;
wire   [7:0] newSel6_fu_1377_p3;
wire   [63:0] tmp_2_fu_1237_p10;
wire   [63:0] tmp_s_fu_1385_p1;
wire   [7:0] tmp_25_fu_1395_p1;
wire   [1:0] knn_mat_6_2_3_fu_1408_p5;
wire   [1:0] knn_mat_6_1_3_fu_1422_p5;
wire   [1:0] knn_mat_6_0_3_fu_1436_p5;
wire   [1:0] knn_mat_5_3_3_fu_1477_p5;
wire   [1:0] knn_mat_5_2_3_fu_1491_p5;
wire   [1:0] knn_mat_5_1_3_fu_1505_p5;
wire   [1:0] knn_mat_5_0_3_fu_1519_p5;
wire   [1:0] knn_mat_4_3_3_fu_1565_p5;
wire   [1:0] knn_mat_4_2_3_fu_1579_p5;
wire   [1:0] knn_mat_4_1_3_fu_1593_p5;
wire   [1:0] knn_mat_4_0_3_fu_1607_p5;
wire   [1:0] knn_mat_3_3_3_fu_1653_p5;
wire   [1:0] knn_mat_3_2_3_fu_1667_p5;
wire   [1:0] knn_mat_3_1_3_fu_1681_p5;
wire   [1:0] knn_mat_3_0_3_fu_1695_p5;
wire   [1:0] knn_mat_2_3_3_fu_1741_p5;
wire   [1:0] knn_mat_2_2_3_fu_1755_p5;
wire   [1:0] knn_mat_2_1_3_fu_1769_p5;
wire   [1:0] knn_mat_2_0_3_fu_1783_p5;
wire   [1:0] knn_mat_1_3_3_fu_1829_p5;
wire   [1:0] knn_mat_1_2_3_fu_1843_p5;
wire   [1:0] knn_mat_1_1_3_fu_1857_p5;
wire   [1:0] knn_mat_1_0_3_fu_1871_p5;
wire   [1:0] knn_mat_0_3_3_fu_1917_p5;
wire   [1:0] knn_mat_0_2_3_fu_1931_p5;
wire   [1:0] knn_mat_0_1_3_fu_1945_p5;
wire   [1:0] knn_mat_0_0_3_fu_1959_p5;
wire   [1:0] knn_mat_7_2_3_fu_2002_p5;
wire   [1:0] knn_mat_7_1_3_fu_2016_p5;
wire   [1:0] knn_mat_7_0_3_fu_2030_p5;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

digitrec_kernel_digitrec_kernel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_32_8_1_1_U13(
    .din0(knn_mat_6_0_fu_168),
    .din1(knn_mat_6_1_fu_164),
    .din2(knn_mat_6_2_fu_160),
    .din3(grp_fu_710_p4),
    .dout(grp_fu_710_p5)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U14(
    .din0(knn_mat_5_0_fu_184),
    .din1(knn_mat_5_1_fu_180),
    .din2(knn_mat_5_2_fu_176),
    .din3(knn_mat_5_3_fu_172),
    .din4(grp_fu_722_p5),
    .dout(grp_fu_722_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U15(
    .din0(knn_mat_4_0_fu_200),
    .din1(knn_mat_4_1_fu_196),
    .din2(knn_mat_4_2_fu_192),
    .din3(knn_mat_4_3_fu_188),
    .din4(grp_fu_736_p5),
    .dout(grp_fu_736_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U16(
    .din0(knn_mat_3_0_fu_216),
    .din1(knn_mat_3_1_fu_212),
    .din2(knn_mat_3_2_fu_208),
    .din3(knn_mat_3_3_fu_204),
    .din4(grp_fu_750_p5),
    .dout(grp_fu_750_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U17(
    .din0(knn_mat_2_0_fu_232),
    .din1(knn_mat_2_1_fu_228),
    .din2(knn_mat_2_2_fu_224),
    .din3(knn_mat_2_3_fu_220),
    .din4(grp_fu_764_p5),
    .dout(grp_fu_764_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U18(
    .din0(knn_mat_1_0_fu_248),
    .din1(knn_mat_1_1_fu_244),
    .din2(knn_mat_1_2_fu_240),
    .din3(knn_mat_1_3_fu_236),
    .din4(grp_fu_778_p5),
    .dout(grp_fu_778_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U19(
    .din0(knn_mat_0_0_fu_264),
    .din1(knn_mat_0_1_fu_260),
    .din2(knn_mat_0_2_fu_256),
    .din3(knn_mat_0_3_fu_252),
    .din4(grp_fu_792_p5),
    .dout(grp_fu_792_p6)
);

digitrec_kernel_digitrec_kernel_mux_32_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_32_8_1_1_U20(
    .din0(knn_mat_7_0_fu_156),
    .din1(knn_mat_7_1_fu_152),
    .din2(knn_mat_7_2_fu_148),
    .din3(grp_fu_806_p4),
    .dout(grp_fu_806_p5)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U21(
    .din0(knn_mat_0_0_fu_264),
    .din1(knn_mat_1_0_fu_248),
    .din2(knn_mat_2_0_fu_232),
    .din3(knn_mat_3_0_fu_216),
    .din4(i1_reg_576),
    .dout(knn_mat_load_2_0_phi_fu_1206_p6)
);

digitrec_kernel_digitrec_kernel_mux_832_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
digitrec_kernel_mux_832_64_1_1_U22(
    .din0(temp_0_q0),
    .din1(temp_1_q0),
    .din2(temp_2_q0),
    .din3(temp_3_q0),
    .din4(temp_4_q0),
    .din5(temp_5_q0),
    .din6(temp_6_q0),
    .din7(temp_7_q0),
    .din8(tmp_2_fu_1237_p9),
    .dout(tmp_2_fu_1237_p10)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U23(
    .din0(knn_mat_6_2_fu_160),
    .din1(knn_mat_6_2_fu_160),
    .din2(tmp_25_fu_1395_p1),
    .din3(tmp_25_fu_1395_p1),
    .din4(knn_mat_6_2_3_fu_1408_p5),
    .dout(knn_mat_6_2_3_fu_1408_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U24(
    .din0(knn_mat_6_1_fu_164),
    .din1(tmp_25_fu_1395_p1),
    .din2(knn_mat_6_1_fu_164),
    .din3(knn_mat_6_1_fu_164),
    .din4(knn_mat_6_1_3_fu_1422_p5),
    .dout(knn_mat_6_1_3_fu_1422_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U25(
    .din0(tmp_25_fu_1395_p1),
    .din1(knn_mat_6_0_fu_168),
    .din2(knn_mat_6_0_fu_168),
    .din3(knn_mat_6_0_fu_168),
    .din4(knn_mat_6_0_3_fu_1436_p5),
    .dout(knn_mat_6_0_3_fu_1436_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U26(
    .din0(knn_mat_5_3_fu_172),
    .din1(knn_mat_5_3_fu_172),
    .din2(knn_mat_5_3_fu_172),
    .din3(tmp_25_fu_1395_p1),
    .din4(knn_mat_5_3_3_fu_1477_p5),
    .dout(knn_mat_5_3_3_fu_1477_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U27(
    .din0(knn_mat_5_2_fu_176),
    .din1(knn_mat_5_2_fu_176),
    .din2(tmp_25_fu_1395_p1),
    .din3(knn_mat_5_2_fu_176),
    .din4(knn_mat_5_2_3_fu_1491_p5),
    .dout(knn_mat_5_2_3_fu_1491_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U28(
    .din0(knn_mat_5_1_fu_180),
    .din1(tmp_25_fu_1395_p1),
    .din2(knn_mat_5_1_fu_180),
    .din3(knn_mat_5_1_fu_180),
    .din4(knn_mat_5_1_3_fu_1505_p5),
    .dout(knn_mat_5_1_3_fu_1505_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U29(
    .din0(tmp_25_fu_1395_p1),
    .din1(knn_mat_5_0_fu_184),
    .din2(knn_mat_5_0_fu_184),
    .din3(knn_mat_5_0_fu_184),
    .din4(knn_mat_5_0_3_fu_1519_p5),
    .dout(knn_mat_5_0_3_fu_1519_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U30(
    .din0(knn_mat_4_3_fu_188),
    .din1(knn_mat_4_3_fu_188),
    .din2(knn_mat_4_3_fu_188),
    .din3(tmp_25_fu_1395_p1),
    .din4(knn_mat_4_3_3_fu_1565_p5),
    .dout(knn_mat_4_3_3_fu_1565_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U31(
    .din0(knn_mat_4_2_fu_192),
    .din1(knn_mat_4_2_fu_192),
    .din2(tmp_25_fu_1395_p1),
    .din3(knn_mat_4_2_fu_192),
    .din4(knn_mat_4_2_3_fu_1579_p5),
    .dout(knn_mat_4_2_3_fu_1579_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U32(
    .din0(knn_mat_4_1_fu_196),
    .din1(tmp_25_fu_1395_p1),
    .din2(knn_mat_4_1_fu_196),
    .din3(knn_mat_4_1_fu_196),
    .din4(knn_mat_4_1_3_fu_1593_p5),
    .dout(knn_mat_4_1_3_fu_1593_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U33(
    .din0(tmp_25_fu_1395_p1),
    .din1(knn_mat_4_0_fu_200),
    .din2(knn_mat_4_0_fu_200),
    .din3(knn_mat_4_0_fu_200),
    .din4(knn_mat_4_0_3_fu_1607_p5),
    .dout(knn_mat_4_0_3_fu_1607_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U34(
    .din0(knn_mat_3_3_fu_204),
    .din1(knn_mat_3_3_fu_204),
    .din2(knn_mat_3_3_fu_204),
    .din3(tmp_25_fu_1395_p1),
    .din4(knn_mat_3_3_3_fu_1653_p5),
    .dout(knn_mat_3_3_3_fu_1653_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U35(
    .din0(knn_mat_3_2_fu_208),
    .din1(knn_mat_3_2_fu_208),
    .din2(tmp_25_fu_1395_p1),
    .din3(knn_mat_3_2_fu_208),
    .din4(knn_mat_3_2_3_fu_1667_p5),
    .dout(knn_mat_3_2_3_fu_1667_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U36(
    .din0(knn_mat_3_1_fu_212),
    .din1(tmp_25_fu_1395_p1),
    .din2(knn_mat_3_1_fu_212),
    .din3(knn_mat_3_1_fu_212),
    .din4(knn_mat_3_1_3_fu_1681_p5),
    .dout(knn_mat_3_1_3_fu_1681_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U37(
    .din0(tmp_25_fu_1395_p1),
    .din1(knn_mat_3_0_fu_216),
    .din2(knn_mat_3_0_fu_216),
    .din3(knn_mat_3_0_fu_216),
    .din4(knn_mat_3_0_3_fu_1695_p5),
    .dout(knn_mat_3_0_3_fu_1695_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U38(
    .din0(knn_mat_2_3_fu_220),
    .din1(knn_mat_2_3_fu_220),
    .din2(knn_mat_2_3_fu_220),
    .din3(tmp_25_fu_1395_p1),
    .din4(knn_mat_2_3_3_fu_1741_p5),
    .dout(knn_mat_2_3_3_fu_1741_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U39(
    .din0(knn_mat_2_2_fu_224),
    .din1(knn_mat_2_2_fu_224),
    .din2(tmp_25_fu_1395_p1),
    .din3(knn_mat_2_2_fu_224),
    .din4(knn_mat_2_2_3_fu_1755_p5),
    .dout(knn_mat_2_2_3_fu_1755_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U40(
    .din0(knn_mat_2_1_fu_228),
    .din1(tmp_25_fu_1395_p1),
    .din2(knn_mat_2_1_fu_228),
    .din3(knn_mat_2_1_fu_228),
    .din4(knn_mat_2_1_3_fu_1769_p5),
    .dout(knn_mat_2_1_3_fu_1769_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U41(
    .din0(tmp_25_fu_1395_p1),
    .din1(knn_mat_2_0_fu_232),
    .din2(knn_mat_2_0_fu_232),
    .din3(knn_mat_2_0_fu_232),
    .din4(knn_mat_2_0_3_fu_1783_p5),
    .dout(knn_mat_2_0_3_fu_1783_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U42(
    .din0(knn_mat_1_3_fu_236),
    .din1(knn_mat_1_3_fu_236),
    .din2(knn_mat_1_3_fu_236),
    .din3(tmp_25_fu_1395_p1),
    .din4(knn_mat_1_3_3_fu_1829_p5),
    .dout(knn_mat_1_3_3_fu_1829_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U43(
    .din0(knn_mat_1_2_fu_240),
    .din1(knn_mat_1_2_fu_240),
    .din2(tmp_25_fu_1395_p1),
    .din3(knn_mat_1_2_fu_240),
    .din4(knn_mat_1_2_3_fu_1843_p5),
    .dout(knn_mat_1_2_3_fu_1843_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U44(
    .din0(knn_mat_1_1_fu_244),
    .din1(tmp_25_fu_1395_p1),
    .din2(knn_mat_1_1_fu_244),
    .din3(knn_mat_1_1_fu_244),
    .din4(knn_mat_1_1_3_fu_1857_p5),
    .dout(knn_mat_1_1_3_fu_1857_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U45(
    .din0(tmp_25_fu_1395_p1),
    .din1(knn_mat_1_0_fu_248),
    .din2(knn_mat_1_0_fu_248),
    .din3(knn_mat_1_0_fu_248),
    .din4(knn_mat_1_0_3_fu_1871_p5),
    .dout(knn_mat_1_0_3_fu_1871_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U46(
    .din0(knn_mat_0_3_fu_252),
    .din1(knn_mat_0_3_fu_252),
    .din2(knn_mat_0_3_fu_252),
    .din3(tmp_25_fu_1395_p1),
    .din4(knn_mat_0_3_3_fu_1917_p5),
    .dout(knn_mat_0_3_3_fu_1917_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U47(
    .din0(knn_mat_0_2_fu_256),
    .din1(knn_mat_0_2_fu_256),
    .din2(tmp_25_fu_1395_p1),
    .din3(knn_mat_0_2_fu_256),
    .din4(knn_mat_0_2_3_fu_1931_p5),
    .dout(knn_mat_0_2_3_fu_1931_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U48(
    .din0(knn_mat_0_1_fu_260),
    .din1(tmp_25_fu_1395_p1),
    .din2(knn_mat_0_1_fu_260),
    .din3(knn_mat_0_1_fu_260),
    .din4(knn_mat_0_1_3_fu_1945_p5),
    .dout(knn_mat_0_1_3_fu_1945_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U49(
    .din0(tmp_25_fu_1395_p1),
    .din1(knn_mat_0_0_fu_264),
    .din2(knn_mat_0_0_fu_264),
    .din3(knn_mat_0_0_fu_264),
    .din4(knn_mat_0_0_3_fu_1959_p5),
    .dout(knn_mat_0_0_3_fu_1959_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U50(
    .din0(knn_mat_7_2_fu_148),
    .din1(knn_mat_7_2_fu_148),
    .din2(tmp_25_fu_1395_p1),
    .din3(tmp_25_fu_1395_p1),
    .din4(knn_mat_7_2_3_fu_2002_p5),
    .dout(knn_mat_7_2_3_fu_2002_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U51(
    .din0(knn_mat_7_1_fu_152),
    .din1(tmp_25_fu_1395_p1),
    .din2(knn_mat_7_1_fu_152),
    .din3(knn_mat_7_1_fu_152),
    .din4(knn_mat_7_1_3_fu_2016_p5),
    .dout(knn_mat_7_1_3_fu_2016_p6)
);

digitrec_kernel_digitrec_kernel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
digitrec_kernel_mux_42_8_1_1_U52(
    .din0(tmp_25_fu_1395_p1),
    .din1(knn_mat_7_0_fu_156),
    .din2(knn_mat_7_0_fu_156),
    .din3(knn_mat_7_0_fu_156),
    .din4(knn_mat_7_0_3_fu_2030_p5),
    .dout(knn_mat_7_0_3_fu_2030_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i1_reg_576 <= i1_1_reg_2310;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_968_p2 == 1'd0))) begin
        i1_reg_576 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd0))) begin
        knn_mat_0_0_fu_264 <= knn_mat_0_0_3_fu_1959_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_0_0_fu_264 <= knn_mat_0_0_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd0))) begin
        knn_mat_0_1_fu_260 <= knn_mat_0_1_3_fu_1945_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_0_1_fu_260 <= knn_mat_0_1_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd0))) begin
        knn_mat_0_2_fu_256 <= knn_mat_0_2_3_fu_1931_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_0_2_fu_256 <= knn_mat_0_2_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd0))) begin
        knn_mat_0_3_fu_252 <= knn_mat_0_3_3_fu_1917_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_0_3_fu_252 <= knn_mat_0_3_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd1))) begin
        knn_mat_1_0_fu_248 <= knn_mat_1_0_3_fu_1871_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_1_0_fu_248 <= knn_mat_1_0_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd1))) begin
        knn_mat_1_1_fu_244 <= knn_mat_1_1_3_fu_1857_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_1_1_fu_244 <= knn_mat_1_1_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd1))) begin
        knn_mat_1_2_fu_240 <= knn_mat_1_2_3_fu_1843_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_1_2_fu_240 <= knn_mat_1_2_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd1))) begin
        knn_mat_1_3_fu_236 <= knn_mat_1_3_3_fu_1829_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_1_3_fu_236 <= knn_mat_1_3_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd2))) begin
        knn_mat_2_0_fu_232 <= knn_mat_2_0_3_fu_1783_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_2_0_fu_232 <= knn_mat_2_0_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd2))) begin
        knn_mat_2_1_fu_228 <= knn_mat_2_1_3_fu_1769_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_2_1_fu_228 <= knn_mat_2_1_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd2))) begin
        knn_mat_2_2_fu_224 <= knn_mat_2_2_3_fu_1755_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_2_2_fu_224 <= knn_mat_2_2_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd2))) begin
        knn_mat_2_3_fu_220 <= knn_mat_2_3_3_fu_1741_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_2_3_fu_220 <= knn_mat_2_3_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd3))) begin
        knn_mat_3_0_fu_216 <= knn_mat_3_0_3_fu_1695_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_3_0_fu_216 <= knn_mat_3_0_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd3))) begin
        knn_mat_3_1_fu_212 <= knn_mat_3_1_3_fu_1681_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_3_1_fu_212 <= knn_mat_3_1_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd3))) begin
        knn_mat_3_2_fu_208 <= knn_mat_3_2_3_fu_1667_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_3_2_fu_208 <= knn_mat_3_2_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd3))) begin
        knn_mat_3_3_fu_204 <= knn_mat_3_3_3_fu_1653_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_3_3_fu_204 <= knn_mat_3_3_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd4))) begin
        knn_mat_4_0_fu_200 <= knn_mat_4_0_3_fu_1607_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_4_0_fu_200 <= knn_mat_4_0_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd4))) begin
        knn_mat_4_1_fu_196 <= knn_mat_4_1_3_fu_1593_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_4_1_fu_196 <= knn_mat_4_1_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd4))) begin
        knn_mat_4_2_fu_192 <= knn_mat_4_2_3_fu_1579_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_4_2_fu_192 <= knn_mat_4_2_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd4))) begin
        knn_mat_4_3_fu_188 <= knn_mat_4_3_3_fu_1565_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_4_3_fu_188 <= knn_mat_4_3_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd5))) begin
        knn_mat_5_0_fu_184 <= knn_mat_5_0_3_fu_1519_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_5_0_fu_184 <= knn_mat_5_0_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd5))) begin
        knn_mat_5_1_fu_180 <= knn_mat_5_1_3_fu_1505_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_5_1_fu_180 <= knn_mat_5_1_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd5))) begin
        knn_mat_5_2_fu_176 <= knn_mat_5_2_3_fu_1491_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_5_2_fu_176 <= knn_mat_5_2_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd5))) begin
        knn_mat_5_3_fu_172 <= knn_mat_5_3_3_fu_1477_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_5_3_fu_172 <= knn_mat_5_3_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd6))) begin
        knn_mat_6_0_fu_168 <= knn_mat_6_0_3_fu_1436_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_6_0_fu_168 <= knn_mat_6_0_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd6))) begin
        knn_mat_6_1_fu_164 <= knn_mat_6_1_3_fu_1422_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_6_1_fu_164 <= knn_mat_6_1_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd6))) begin
        knn_mat_6_2_fu_160 <= knn_mat_6_2_3_fu_1408_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_6_2_fu_160 <= knn_mat_6_2_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd7))) begin
        knn_mat_7_0_fu_156 <= knn_mat_7_0_3_fu_2030_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_7_0_fu_156 <= knn_mat_7_0_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd7))) begin
        knn_mat_7_1_fu_152 <= knn_mat_7_1_3_fu_2016_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_7_1_fu_152 <= knn_mat_7_1_read;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_11_fu_1389_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_23_fu_1259_p1 == 3'd7))) begin
        knn_mat_7_2_fu_148 <= knn_mat_7_2_3_fu_2002_p6;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        knn_mat_7_2_fu_148 <= knn_mat_7_2_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_1160_p2 == 1'd0))) begin
        if ((tmp_24_fu_1172_p1 == 3'd7)) begin
            knn_mat_load_1_0_phi_reg_588 <= grp_fu_806_p5;
        end else if ((tmp_24_fu_1172_p1 == 3'd6)) begin
            knn_mat_load_1_0_phi_reg_588 <= grp_fu_710_p5;
        end else if ((tmp_24_fu_1172_p1 == 3'd5)) begin
            knn_mat_load_1_0_phi_reg_588 <= grp_fu_722_p6;
        end else if ((tmp_24_fu_1172_p1 == 3'd4)) begin
            knn_mat_load_1_0_phi_reg_588 <= grp_fu_736_p6;
        end else if ((tmp_24_fu_1172_p1 == 3'd3)) begin
            knn_mat_load_1_0_phi_reg_588 <= grp_fu_750_p6;
        end else if ((tmp_24_fu_1172_p1 == 3'd2)) begin
            knn_mat_load_1_0_phi_reg_588 <= grp_fu_764_p6;
        end else if ((tmp_24_fu_1172_p1 == 3'd1)) begin
            knn_mat_load_1_0_phi_reg_588 <= grp_fu_778_p6;
        end else if ((tmp_24_fu_1172_p1 == 3'd0)) begin
            knn_mat_load_1_0_phi_reg_588 <= grp_fu_792_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        max_id_reg_564 <= p_max_id_fu_1226_p3;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond1_fu_968_p2 == 1'd0))) begin
        max_id_reg_564 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y3_reg_552 <= y3_1_reg_2302;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        y3_reg_552 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i1_1_reg_2310 <= i1_1_fu_1166_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond_fu_1160_p2 == 1'd1))) begin
        tmp_12_reg_2358 <= tmp_12_fu_1176_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y3_1_reg_2302 <= y3_1_fu_974_p2;
    end
end

always @ (*) begin
    if ((((exitcond1_fu_968_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_968_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_699_p1 = max_id_reg_564;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_699_p1 = ap_phi_mux_max_id_phi_fu_568_p4;
    end else begin
        grp_fu_699_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp_0_ce0 = 1'b1;
    end else begin
        temp_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp_1_ce0 = 1'b1;
    end else begin
        temp_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp_2_ce0 = 1'b1;
    end else begin
        temp_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp_3_ce0 = 1'b1;
    end else begin
        temp_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp_4_ce0 = 1'b1;
    end else begin
        temp_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp_5_ce0 = 1'b1;
    end else begin
        temp_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp_6_ce0 = 1'b1;
    end else begin
        temp_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        temp_7_ce0 = 1'b1;
    end else begin
        temp_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_fu_968_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (((tmp_24_fu_1172_p1 == 3'd7) & (exitcond_fu_1160_p2 == 1'd0)) | ((tmp_24_fu_1172_p1 == 3'd0) & (exitcond_fu_1160_p2 == 1'd0)) | ((tmp_24_fu_1172_p1 == 3'd1) & (exitcond_fu_1160_p2 == 1'd0)) | ((tmp_24_fu_1172_p1 == 3'd2) & (exitcond_fu_1160_p2 == 1'd0)) | ((tmp_24_fu_1172_p1 == 3'd3) & (exitcond_fu_1160_p2 == 1'd0)) | ((tmp_24_fu_1172_p1 == 3'd4) & (exitcond_fu_1160_p2 == 1'd0)) | ((tmp_24_fu_1172_p1 == 3'd5) & (exitcond_fu_1160_p2 == 1'd0)) | ((tmp_24_fu_1172_p1 == 3'd6) & (exitcond_fu_1160_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_phi_mux_max_id_phi_fu_568_p4 = max_id_reg_564;

assign ap_return_0 = knn_mat_0_0_fu_264;

assign ap_return_1 = knn_mat_0_1_fu_260;

assign ap_return_10 = knn_mat_2_2_fu_224;

assign ap_return_11 = knn_mat_2_3_fu_220;

assign ap_return_12 = knn_mat_3_0_fu_216;

assign ap_return_13 = knn_mat_3_1_fu_212;

assign ap_return_14 = knn_mat_3_2_fu_208;

assign ap_return_15 = knn_mat_3_3_fu_204;

assign ap_return_16 = knn_mat_4_0_fu_200;

assign ap_return_17 = knn_mat_4_1_fu_196;

assign ap_return_18 = knn_mat_4_2_fu_192;

assign ap_return_19 = knn_mat_4_3_fu_188;

assign ap_return_2 = knn_mat_0_2_fu_256;

assign ap_return_20 = knn_mat_5_0_fu_184;

assign ap_return_21 = knn_mat_5_1_fu_180;

assign ap_return_22 = knn_mat_5_2_fu_176;

assign ap_return_23 = knn_mat_5_3_fu_172;

assign ap_return_24 = knn_mat_6_0_fu_168;

assign ap_return_25 = knn_mat_6_1_fu_164;

assign ap_return_26 = knn_mat_6_2_fu_160;

assign ap_return_27 = knn_mat_7_0_fu_156;

assign ap_return_28 = knn_mat_7_1_fu_152;

assign ap_return_29 = knn_mat_7_2_fu_148;

assign ap_return_3 = knn_mat_0_3_fu_252;

assign ap_return_4 = knn_mat_1_0_fu_248;

assign ap_return_5 = knn_mat_1_1_fu_244;

assign ap_return_6 = knn_mat_1_2_fu_240;

assign ap_return_7 = knn_mat_1_3_fu_236;

assign ap_return_8 = knn_mat_2_0_fu_232;

assign ap_return_9 = knn_mat_2_1_fu_228;

assign exitcond1_fu_968_p2 = ((y3_reg_552 == 11'd1800) ? 1'b1 : 1'b0);

assign exitcond_fu_1160_p2 = ((i1_reg_576 == 2'd3) ? 1'b1 : 1'b0);

assign grp_fu_710_p4 = {{grp_fu_699_p1[4:3]}};

assign grp_fu_722_p5 = {{grp_fu_699_p1[4:3]}};

assign grp_fu_736_p5 = {{grp_fu_699_p1[4:3]}};

assign grp_fu_750_p5 = {{grp_fu_699_p1[4:3]}};

assign grp_fu_764_p5 = {{grp_fu_699_p1[4:3]}};

assign grp_fu_778_p5 = {{grp_fu_699_p1[4:3]}};

assign grp_fu_792_p5 = {{grp_fu_699_p1[4:3]}};

assign grp_fu_806_p4 = {{grp_fu_699_p1[4:3]}};

assign i1_1_fu_1166_p2 = (i1_reg_576 + 2'd1);

assign knn_mat_0_0_3_fu_1959_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_0_1_3_fu_1945_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_0_2_3_fu_1931_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_0_3_3_fu_1917_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_1_0_3_fu_1871_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_1_1_3_fu_1857_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_1_2_3_fu_1843_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_1_3_3_fu_1829_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_2_0_3_fu_1783_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_2_1_3_fu_1769_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_2_2_3_fu_1755_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_2_3_3_fu_1741_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_3_0_3_fu_1695_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_3_1_3_fu_1681_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_3_2_3_fu_1667_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_3_3_3_fu_1653_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_4_0_3_fu_1607_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_4_1_3_fu_1593_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_4_2_3_fu_1579_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_4_3_3_fu_1565_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_5_0_3_fu_1519_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_5_1_3_fu_1505_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_5_2_3_fu_1491_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_5_3_3_fu_1477_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_6_0_3_fu_1436_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_6_1_3_fu_1422_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_6_2_3_fu_1408_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_7_0_3_fu_2030_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_7_1_3_fu_2016_p5 = {{grp_fu_699_p1[4:3]}};

assign knn_mat_7_2_3_fu_2002_p5 = {{grp_fu_699_p1[4:3]}};

assign newIndex1_fu_1190_p1 = newIndex_fu_1180_p4;

assign newIndex_fu_1180_p4 = {{y3_reg_552[10:3]}};

assign newSel1_fu_1319_p3 = ((sel_tmp8_fu_1287_p2[0:0] === 1'b1) ? grp_fu_736_p6 : grp_fu_750_p6);

assign newSel2_fu_1333_p3 = ((sel_tmp4_fu_1275_p2[0:0] === 1'b1) ? grp_fu_764_p6 : grp_fu_778_p6);

assign newSel3_fu_1347_p3 = ((sel_tmp_fu_1263_p2[0:0] === 1'b1) ? grp_fu_792_p6 : grp_fu_806_p5);

assign newSel4_fu_1355_p3 = ((or_cond_fu_1313_p2[0:0] === 1'b1) ? newSel_fu_1305_p3 : newSel1_fu_1319_p3);

assign newSel5_fu_1369_p3 = ((or_cond2_fu_1341_p2[0:0] === 1'b1) ? newSel2_fu_1333_p3 : newSel3_fu_1347_p3);

assign newSel6_fu_1377_p3 = ((or_cond3_fu_1363_p2[0:0] === 1'b1) ? newSel4_fu_1355_p3 : newSel5_fu_1369_p3);

assign newSel_fu_1305_p3 = ((sel_tmp3_fu_1299_p2[0:0] === 1'b1) ? grp_fu_710_p5 : grp_fu_722_p6);

assign or_cond1_fu_1327_p2 = (sel_tmp8_fu_1287_p2 | sel_tmp6_fu_1281_p2);

assign or_cond2_fu_1341_p2 = (sel_tmp4_fu_1275_p2 | sel_tmp2_fu_1269_p2);

assign or_cond3_fu_1363_p2 = (or_cond_fu_1313_p2 | or_cond1_fu_1327_p2);

assign or_cond_fu_1313_p2 = (sel_tmp3_fu_1299_p2 | sel_tmp1_fu_1293_p2);

assign p_max_id_fu_1226_p3 = ((tmp_22_fu_1220_p2[0:0] === 1'b1) ? tmp_21_fu_1202_p1 : max_id_reg_564);

assign sel_tmp1_fu_1293_p2 = ((tmp_23_fu_1259_p1 == 3'd5) ? 1'b1 : 1'b0);

assign sel_tmp2_fu_1269_p2 = ((tmp_23_fu_1259_p1 == 3'd1) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_1299_p2 = ((tmp_23_fu_1259_p1 == 3'd6) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_1275_p2 = ((tmp_23_fu_1259_p1 == 3'd2) ? 1'b1 : 1'b0);

assign sel_tmp6_fu_1281_p2 = ((tmp_23_fu_1259_p1 == 3'd3) ? 1'b1 : 1'b0);

assign sel_tmp8_fu_1287_p2 = ((tmp_23_fu_1259_p1 == 3'd4) ? 1'b1 : 1'b0);

assign sel_tmp_fu_1263_p2 = ((tmp_23_fu_1259_p1 == 3'd0) ? 1'b1 : 1'b0);

assign temp_0_address0 = newIndex1_fu_1190_p1;

assign temp_1_address0 = newIndex1_fu_1190_p1;

assign temp_2_address0 = newIndex1_fu_1190_p1;

assign temp_3_address0 = newIndex1_fu_1190_p1;

assign temp_4_address0 = newIndex1_fu_1190_p1;

assign temp_5_address0 = newIndex1_fu_1190_p1;

assign temp_6_address0 = newIndex1_fu_1190_p1;

assign temp_7_address0 = newIndex1_fu_1190_p1;

assign tmp_11_fu_1389_p2 = ((tmp_2_fu_1237_p10 < tmp_s_fu_1385_p1) ? 1'b1 : 1'b0);

assign tmp_12_fu_1176_p1 = y3_reg_552[2:0];

assign tmp_21_fu_1202_p1 = i1_reg_576;

assign tmp_22_fu_1220_p2 = ((knn_mat_load_1_0_phi_reg_588 < knn_mat_load_2_0_phi_fu_1206_p6) ? 1'b1 : 1'b0);

assign tmp_23_fu_1259_p1 = max_id_reg_564[2:0];

assign tmp_24_fu_1172_p1 = max_id_reg_564[2:0];

assign tmp_25_fu_1395_p1 = tmp_2_fu_1237_p10[7:0];

assign tmp_2_fu_1237_p9 = tmp_12_reg_2358;

assign tmp_s_fu_1385_p1 = newSel6_fu_1377_p3;

assign y3_1_fu_974_p2 = (y3_reg_552 + 11'd1);

endmodule //digitrec_kernel_update
