// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2_AR71275_op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "digitrec_kernel_load_unsigned_long_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic digitrec_kernel_load_unsigned_long_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic digitrec_kernel_load_unsigned_long_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state1 = "1";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state2 = "10";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state3 = "100";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state4 = "1000";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state5 = "10000";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state6 = "100000";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_pp0_stage0 = "100000000";
const sc_lv<10> digitrec_kernel_load_unsigned_long_s::ap_ST_fsm_state12 = "1000000000";
const bool digitrec_kernel_load_unsigned_long_s::ap_const_boolean_1 = true;
const sc_lv<32> digitrec_kernel_load_unsigned_long_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<64> digitrec_kernel_load_unsigned_long_s::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<1> digitrec_kernel_load_unsigned_long_s::ap_const_lv1_0 = "0";
const sc_lv<3> digitrec_kernel_load_unsigned_long_s::ap_const_lv3_0 = "000";
const sc_lv<2> digitrec_kernel_load_unsigned_long_s::ap_const_lv2_0 = "00";
const sc_lv<4> digitrec_kernel_load_unsigned_long_s::ap_const_lv4_0 = "0000";
const sc_lv<8> digitrec_kernel_load_unsigned_long_s::ap_const_lv8_0 = "00000000";
const sc_lv<32> digitrec_kernel_load_unsigned_long_s::ap_const_lv32_1 = "1";
const sc_lv<32> digitrec_kernel_load_unsigned_long_s::ap_const_lv32_8 = "1000";
const bool digitrec_kernel_load_unsigned_long_s::ap_const_boolean_0 = false;
const sc_lv<32> digitrec_kernel_load_unsigned_long_s::ap_const_lv32_7 = "111";
const sc_lv<1> digitrec_kernel_load_unsigned_long_s::ap_const_lv1_1 = "1";
const sc_lv<11> digitrec_kernel_load_unsigned_long_s::ap_const_lv11_0 = "00000000000";
const sc_lv<3> digitrec_kernel_load_unsigned_long_s::ap_const_lv3_6 = "110";
const sc_lv<3> digitrec_kernel_load_unsigned_long_s::ap_const_lv3_5 = "101";
const sc_lv<3> digitrec_kernel_load_unsigned_long_s::ap_const_lv3_4 = "100";
const sc_lv<3> digitrec_kernel_load_unsigned_long_s::ap_const_lv3_3 = "11";
const sc_lv<3> digitrec_kernel_load_unsigned_long_s::ap_const_lv3_2 = "10";
const sc_lv<3> digitrec_kernel_load_unsigned_long_s::ap_const_lv3_1 = "1";
const sc_lv<3> digitrec_kernel_load_unsigned_long_s::ap_const_lv3_7 = "111";
const sc_lv<11> digitrec_kernel_load_unsigned_long_s::ap_const_lv11_1 = "1";
const sc_lv<32> digitrec_kernel_load_unsigned_long_s::ap_const_lv32_3 = "11";
const sc_lv<32> digitrec_kernel_load_unsigned_long_s::ap_const_lv32_A = "1010";
const sc_lv<32> digitrec_kernel_load_unsigned_long_s::ap_const_lv32_9 = "1001";

digitrec_kernel_load_unsigned_long_s::digitrec_kernel_load_unsigned_long_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( m_axi_data_dram_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( m_axi_data_dram_RVALID );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter1);
    sensitive << ( m_axi_data_dram_RVALID );

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter0);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state9);
    sensitive << ( exitcond_fu_265_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_sig_ioackin_m_axi_data_dram_ARREADY);
    sensitive << ( m_axi_data_dram_ARREADY );
    sensitive << ( ap_reg_ioackin_m_axi_data_dram_ARREADY );

    SC_METHOD(thread_data_dram_blk_n_AR);
    sensitive << ( m_axi_data_dram_ARREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_data_dram_blk_n_R);
    sensitive << ( m_axi_data_dram_RVALID );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_data_dram_offset_cast_fu_240_p1);
    sensitive << ( data_dram_offset );

    SC_METHOD(thread_data_local_0_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( newIndex8_fu_290_p1 );

    SC_METHOD(thread_data_local_0_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_0_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_dram_addr_read_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_0_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_reg_331_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_1_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( newIndex8_fu_290_p1 );

    SC_METHOD(thread_data_local_1_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_1_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_dram_addr_read_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_1_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_reg_331_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_2_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( newIndex8_fu_290_p1 );

    SC_METHOD(thread_data_local_2_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_2_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_dram_addr_read_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_2_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_reg_331_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_3_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( newIndex8_fu_290_p1 );

    SC_METHOD(thread_data_local_3_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_3_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_dram_addr_read_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_3_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_reg_331_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_4_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( newIndex8_fu_290_p1 );

    SC_METHOD(thread_data_local_4_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_4_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_dram_addr_read_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_4_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_reg_331_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_5_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( newIndex8_fu_290_p1 );

    SC_METHOD(thread_data_local_5_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_5_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_dram_addr_read_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_5_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_reg_331_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_6_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( newIndex8_fu_290_p1 );

    SC_METHOD(thread_data_local_6_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_6_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_dram_addr_read_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_6_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_reg_331_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_7_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( newIndex8_fu_290_p1 );

    SC_METHOD(thread_data_local_7_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_7_d0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( data_dram_addr_read_reg_340 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_data_local_7_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_reg_331_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_exitcond_fu_265_p2);
    sensitive << ( num_elem );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_reg_225 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_i_1_fu_270_p2);
    sensitive << ( i_reg_225 );

    SC_METHOD(thread_m_axi_data_dram_ARADDR);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sum2_cast_fu_250_p1 );
    sensitive << ( ap_reg_ioackin_m_axi_data_dram_ARREADY );

    SC_METHOD(thread_m_axi_data_dram_ARBURST);

    SC_METHOD(thread_m_axi_data_dram_ARCACHE);

    SC_METHOD(thread_m_axi_data_dram_ARID);

    SC_METHOD(thread_m_axi_data_dram_ARLEN);
    sensitive << ( num_elem );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_reg_ioackin_m_axi_data_dram_ARREADY );

    SC_METHOD(thread_m_axi_data_dram_ARLOCK);

    SC_METHOD(thread_m_axi_data_dram_ARPROT);

    SC_METHOD(thread_m_axi_data_dram_ARQOS);

    SC_METHOD(thread_m_axi_data_dram_ARREGION);

    SC_METHOD(thread_m_axi_data_dram_ARSIZE);

    SC_METHOD(thread_m_axi_data_dram_ARUSER);

    SC_METHOD(thread_m_axi_data_dram_ARVALID);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_reg_ioackin_m_axi_data_dram_ARREADY );

    SC_METHOD(thread_m_axi_data_dram_AWADDR);

    SC_METHOD(thread_m_axi_data_dram_AWBURST);

    SC_METHOD(thread_m_axi_data_dram_AWCACHE);

    SC_METHOD(thread_m_axi_data_dram_AWID);

    SC_METHOD(thread_m_axi_data_dram_AWLEN);

    SC_METHOD(thread_m_axi_data_dram_AWLOCK);

    SC_METHOD(thread_m_axi_data_dram_AWPROT);

    SC_METHOD(thread_m_axi_data_dram_AWQOS);

    SC_METHOD(thread_m_axi_data_dram_AWREGION);

    SC_METHOD(thread_m_axi_data_dram_AWSIZE);

    SC_METHOD(thread_m_axi_data_dram_AWUSER);

    SC_METHOD(thread_m_axi_data_dram_AWVALID);

    SC_METHOD(thread_m_axi_data_dram_BREADY);

    SC_METHOD(thread_m_axi_data_dram_RREADY);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_m_axi_data_dram_WDATA);

    SC_METHOD(thread_m_axi_data_dram_WID);

    SC_METHOD(thread_m_axi_data_dram_WLAST);

    SC_METHOD(thread_m_axi_data_dram_WSTRB);

    SC_METHOD(thread_m_axi_data_dram_WUSER);

    SC_METHOD(thread_m_axi_data_dram_WVALID);

    SC_METHOD(thread_newIndex8_fu_290_p1);
    sensitive << ( newIndex_reg_335_pp0_iter1_reg );

    SC_METHOD(thread_sum2_cast_fu_250_p1);
    sensitive << ( sum2_reg_301 );

    SC_METHOD(thread_sum2_fu_244_p2);
    sensitive << ( data_dram_offset_cast_fu_240_p1 );
    sensitive << ( tmp_23_cast_fu_236_p1 );

    SC_METHOD(thread_tmp_23_cast_fu_236_p1);
    sensitive << ( data_dram_offset1 );

    SC_METHOD(thread_tmp_fu_276_p1);
    sensitive << ( i_reg_225 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_sig_ioackin_m_axi_data_dram_ARREADY );
    sensitive << ( exitcond_fu_265_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    ap_CS_fsm = "0000000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_reg_ioackin_m_axi_data_dram_ARREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "digitrec_kernel_load_unsigned_long_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_data_dram_AWVALID, "(port)m_axi_data_dram_AWVALID");
    sc_trace(mVcdFile, m_axi_data_dram_AWREADY, "(port)m_axi_data_dram_AWREADY");
    sc_trace(mVcdFile, m_axi_data_dram_AWADDR, "(port)m_axi_data_dram_AWADDR");
    sc_trace(mVcdFile, m_axi_data_dram_AWID, "(port)m_axi_data_dram_AWID");
    sc_trace(mVcdFile, m_axi_data_dram_AWLEN, "(port)m_axi_data_dram_AWLEN");
    sc_trace(mVcdFile, m_axi_data_dram_AWSIZE, "(port)m_axi_data_dram_AWSIZE");
    sc_trace(mVcdFile, m_axi_data_dram_AWBURST, "(port)m_axi_data_dram_AWBURST");
    sc_trace(mVcdFile, m_axi_data_dram_AWLOCK, "(port)m_axi_data_dram_AWLOCK");
    sc_trace(mVcdFile, m_axi_data_dram_AWCACHE, "(port)m_axi_data_dram_AWCACHE");
    sc_trace(mVcdFile, m_axi_data_dram_AWPROT, "(port)m_axi_data_dram_AWPROT");
    sc_trace(mVcdFile, m_axi_data_dram_AWQOS, "(port)m_axi_data_dram_AWQOS");
    sc_trace(mVcdFile, m_axi_data_dram_AWREGION, "(port)m_axi_data_dram_AWREGION");
    sc_trace(mVcdFile, m_axi_data_dram_AWUSER, "(port)m_axi_data_dram_AWUSER");
    sc_trace(mVcdFile, m_axi_data_dram_WVALID, "(port)m_axi_data_dram_WVALID");
    sc_trace(mVcdFile, m_axi_data_dram_WREADY, "(port)m_axi_data_dram_WREADY");
    sc_trace(mVcdFile, m_axi_data_dram_WDATA, "(port)m_axi_data_dram_WDATA");
    sc_trace(mVcdFile, m_axi_data_dram_WSTRB, "(port)m_axi_data_dram_WSTRB");
    sc_trace(mVcdFile, m_axi_data_dram_WLAST, "(port)m_axi_data_dram_WLAST");
    sc_trace(mVcdFile, m_axi_data_dram_WID, "(port)m_axi_data_dram_WID");
    sc_trace(mVcdFile, m_axi_data_dram_WUSER, "(port)m_axi_data_dram_WUSER");
    sc_trace(mVcdFile, m_axi_data_dram_ARVALID, "(port)m_axi_data_dram_ARVALID");
    sc_trace(mVcdFile, m_axi_data_dram_ARREADY, "(port)m_axi_data_dram_ARREADY");
    sc_trace(mVcdFile, m_axi_data_dram_ARADDR, "(port)m_axi_data_dram_ARADDR");
    sc_trace(mVcdFile, m_axi_data_dram_ARID, "(port)m_axi_data_dram_ARID");
    sc_trace(mVcdFile, m_axi_data_dram_ARLEN, "(port)m_axi_data_dram_ARLEN");
    sc_trace(mVcdFile, m_axi_data_dram_ARSIZE, "(port)m_axi_data_dram_ARSIZE");
    sc_trace(mVcdFile, m_axi_data_dram_ARBURST, "(port)m_axi_data_dram_ARBURST");
    sc_trace(mVcdFile, m_axi_data_dram_ARLOCK, "(port)m_axi_data_dram_ARLOCK");
    sc_trace(mVcdFile, m_axi_data_dram_ARCACHE, "(port)m_axi_data_dram_ARCACHE");
    sc_trace(mVcdFile, m_axi_data_dram_ARPROT, "(port)m_axi_data_dram_ARPROT");
    sc_trace(mVcdFile, m_axi_data_dram_ARQOS, "(port)m_axi_data_dram_ARQOS");
    sc_trace(mVcdFile, m_axi_data_dram_ARREGION, "(port)m_axi_data_dram_ARREGION");
    sc_trace(mVcdFile, m_axi_data_dram_ARUSER, "(port)m_axi_data_dram_ARUSER");
    sc_trace(mVcdFile, m_axi_data_dram_RVALID, "(port)m_axi_data_dram_RVALID");
    sc_trace(mVcdFile, m_axi_data_dram_RREADY, "(port)m_axi_data_dram_RREADY");
    sc_trace(mVcdFile, m_axi_data_dram_RDATA, "(port)m_axi_data_dram_RDATA");
    sc_trace(mVcdFile, m_axi_data_dram_RLAST, "(port)m_axi_data_dram_RLAST");
    sc_trace(mVcdFile, m_axi_data_dram_RID, "(port)m_axi_data_dram_RID");
    sc_trace(mVcdFile, m_axi_data_dram_RUSER, "(port)m_axi_data_dram_RUSER");
    sc_trace(mVcdFile, m_axi_data_dram_RRESP, "(port)m_axi_data_dram_RRESP");
    sc_trace(mVcdFile, m_axi_data_dram_BVALID, "(port)m_axi_data_dram_BVALID");
    sc_trace(mVcdFile, m_axi_data_dram_BREADY, "(port)m_axi_data_dram_BREADY");
    sc_trace(mVcdFile, m_axi_data_dram_BRESP, "(port)m_axi_data_dram_BRESP");
    sc_trace(mVcdFile, m_axi_data_dram_BID, "(port)m_axi_data_dram_BID");
    sc_trace(mVcdFile, m_axi_data_dram_BUSER, "(port)m_axi_data_dram_BUSER");
    sc_trace(mVcdFile, data_dram_offset, "(port)data_dram_offset");
    sc_trace(mVcdFile, data_dram_offset1, "(port)data_dram_offset1");
    sc_trace(mVcdFile, data_local_0_address0, "(port)data_local_0_address0");
    sc_trace(mVcdFile, data_local_0_ce0, "(port)data_local_0_ce0");
    sc_trace(mVcdFile, data_local_0_we0, "(port)data_local_0_we0");
    sc_trace(mVcdFile, data_local_0_d0, "(port)data_local_0_d0");
    sc_trace(mVcdFile, data_local_1_address0, "(port)data_local_1_address0");
    sc_trace(mVcdFile, data_local_1_ce0, "(port)data_local_1_ce0");
    sc_trace(mVcdFile, data_local_1_we0, "(port)data_local_1_we0");
    sc_trace(mVcdFile, data_local_1_d0, "(port)data_local_1_d0");
    sc_trace(mVcdFile, data_local_2_address0, "(port)data_local_2_address0");
    sc_trace(mVcdFile, data_local_2_ce0, "(port)data_local_2_ce0");
    sc_trace(mVcdFile, data_local_2_we0, "(port)data_local_2_we0");
    sc_trace(mVcdFile, data_local_2_d0, "(port)data_local_2_d0");
    sc_trace(mVcdFile, data_local_3_address0, "(port)data_local_3_address0");
    sc_trace(mVcdFile, data_local_3_ce0, "(port)data_local_3_ce0");
    sc_trace(mVcdFile, data_local_3_we0, "(port)data_local_3_we0");
    sc_trace(mVcdFile, data_local_3_d0, "(port)data_local_3_d0");
    sc_trace(mVcdFile, data_local_4_address0, "(port)data_local_4_address0");
    sc_trace(mVcdFile, data_local_4_ce0, "(port)data_local_4_ce0");
    sc_trace(mVcdFile, data_local_4_we0, "(port)data_local_4_we0");
    sc_trace(mVcdFile, data_local_4_d0, "(port)data_local_4_d0");
    sc_trace(mVcdFile, data_local_5_address0, "(port)data_local_5_address0");
    sc_trace(mVcdFile, data_local_5_ce0, "(port)data_local_5_ce0");
    sc_trace(mVcdFile, data_local_5_we0, "(port)data_local_5_we0");
    sc_trace(mVcdFile, data_local_5_d0, "(port)data_local_5_d0");
    sc_trace(mVcdFile, data_local_6_address0, "(port)data_local_6_address0");
    sc_trace(mVcdFile, data_local_6_ce0, "(port)data_local_6_ce0");
    sc_trace(mVcdFile, data_local_6_we0, "(port)data_local_6_we0");
    sc_trace(mVcdFile, data_local_6_d0, "(port)data_local_6_d0");
    sc_trace(mVcdFile, data_local_7_address0, "(port)data_local_7_address0");
    sc_trace(mVcdFile, data_local_7_ce0, "(port)data_local_7_ce0");
    sc_trace(mVcdFile, data_local_7_we0, "(port)data_local_7_we0");
    sc_trace(mVcdFile, data_local_7_d0, "(port)data_local_7_d0");
    sc_trace(mVcdFile, num_elem, "(port)num_elem");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, data_dram_blk_n_AR, "data_dram_blk_n_AR");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, data_dram_blk_n_R, "data_dram_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, i_reg_225, "i_reg_225");
    sc_trace(mVcdFile, sum2_fu_244_p2, "sum2_fu_244_p2");
    sc_trace(mVcdFile, sum2_reg_301, "sum2_reg_301");
    sc_trace(mVcdFile, ap_sig_ioackin_m_axi_data_dram_ARREADY, "ap_sig_ioackin_m_axi_data_dram_ARREADY");
    sc_trace(mVcdFile, exitcond_fu_265_p2, "exitcond_fu_265_p2");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter0, "ap_block_state9_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter1, "ap_block_state10_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter2, "ap_block_state11_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_1_fu_270_p2, "i_1_fu_270_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_fu_276_p1, "tmp_fu_276_p1");
    sc_trace(mVcdFile, tmp_reg_331, "tmp_reg_331");
    sc_trace(mVcdFile, tmp_reg_331_pp0_iter1_reg, "tmp_reg_331_pp0_iter1_reg");
    sc_trace(mVcdFile, newIndex_reg_335, "newIndex_reg_335");
    sc_trace(mVcdFile, newIndex_reg_335_pp0_iter1_reg, "newIndex_reg_335_pp0_iter1_reg");
    sc_trace(mVcdFile, data_dram_addr_read_reg_340, "data_dram_addr_read_reg_340");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state9, "ap_condition_pp0_exit_iter0_state9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, newIndex8_fu_290_p1, "newIndex8_fu_290_p1");
    sc_trace(mVcdFile, sum2_cast_fu_250_p1, "sum2_cast_fu_250_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_m_axi_data_dram_ARREADY, "ap_reg_ioackin_m_axi_data_dram_ARREADY");
    sc_trace(mVcdFile, data_dram_offset_cast_fu_240_p1, "data_dram_offset_cast_fu_240_p1");
    sc_trace(mVcdFile, tmp_23_cast_fu_236_p1, "tmp_23_cast_fu_236_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

digitrec_kernel_load_unsigned_long_s::~digitrec_kernel_load_unsigned_long_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void digitrec_kernel_load_unsigned_long_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state9.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state9.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state9.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ioackin_m_axi_data_dram_ARREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
            if (esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_data_dram_ARREADY.read(), ap_const_logic_1)) {
                ap_reg_ioackin_m_axi_data_dram_ARREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, m_axi_data_dram_ARREADY.read())) {
                ap_reg_ioackin_m_axi_data_dram_ARREADY = ap_const_logic_1;
            }
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_265_p2.read()))) {
        i_reg_225 = i_1_fu_270_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_reg_225 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_dram_addr_read_reg_340 = m_axi_data_dram_RDATA.read();
        newIndex_reg_335_pp0_iter1_reg = newIndex_reg_335.read();
        tmp_reg_331_pp0_iter1_reg = tmp_reg_331.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_265_p2.read()))) {
        newIndex_reg_335 = i_reg_225.read().range(10, 3);
        tmp_reg_331 = tmp_fu_276_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        sum2_reg_301 = sum2_fu_244_p2.read();
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[8];
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[9];
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_0, m_axi_data_dram_RVALID.read()));
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_0, m_axi_data_dram_RVALID.read()));
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_block_state10_pp0_stage0_iter1() {
    ap_block_state10_pp0_stage0_iter1 = esl_seteq<1,1,1>(ap_const_logic_0, m_axi_data_dram_RVALID.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_block_state11_pp0_stage0_iter2() {
    ap_block_state11_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_block_state9_pp0_stage0_iter0() {
    ap_block_state9_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_condition_pp0_exit_iter0_state9() {
    if (esl_seteq<1,1,1>(exitcond_fu_265_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state9 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state9 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_sig_ioackin_m_axi_data_dram_ARREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_data_dram_ARREADY.read())) {
        ap_sig_ioackin_m_axi_data_dram_ARREADY = m_axi_data_dram_ARREADY.read();
    } else {
        ap_sig_ioackin_m_axi_data_dram_ARREADY = ap_const_logic_1;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_dram_blk_n_AR() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        data_dram_blk_n_AR = m_axi_data_dram_ARREADY.read();
    } else {
        data_dram_blk_n_AR = ap_const_logic_1;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_dram_blk_n_R() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        data_dram_blk_n_R = m_axi_data_dram_RVALID.read();
    } else {
        data_dram_blk_n_R = ap_const_logic_1;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_dram_offset_cast_fu_240_p1() {
    data_dram_offset_cast_fu_240_p1 = esl_zext<62,61>(data_dram_offset.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_0_address0() {
    data_local_0_address0 =  (sc_lv<8>) (newIndex8_fu_290_p1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        data_local_0_ce0 = ap_const_logic_1;
    } else {
        data_local_0_ce0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_0_d0() {
    data_local_0_d0 = data_dram_addr_read_reg_340.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_0_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,3,3>(ap_const_lv3_0, tmp_reg_331_pp0_iter1_reg.read()))) {
        data_local_0_we0 = ap_const_logic_1;
    } else {
        data_local_0_we0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_1_address0() {
    data_local_1_address0 =  (sc_lv<8>) (newIndex8_fu_290_p1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        data_local_1_ce0 = ap_const_logic_1;
    } else {
        data_local_1_ce0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_1_d0() {
    data_local_1_d0 = data_dram_addr_read_reg_340.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_1_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,3,3>(tmp_reg_331_pp0_iter1_reg.read(), ap_const_lv3_1))) {
        data_local_1_we0 = ap_const_logic_1;
    } else {
        data_local_1_we0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_2_address0() {
    data_local_2_address0 =  (sc_lv<8>) (newIndex8_fu_290_p1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        data_local_2_ce0 = ap_const_logic_1;
    } else {
        data_local_2_ce0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_2_d0() {
    data_local_2_d0 = data_dram_addr_read_reg_340.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_2_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,3,3>(tmp_reg_331_pp0_iter1_reg.read(), ap_const_lv3_2))) {
        data_local_2_we0 = ap_const_logic_1;
    } else {
        data_local_2_we0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_3_address0() {
    data_local_3_address0 =  (sc_lv<8>) (newIndex8_fu_290_p1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        data_local_3_ce0 = ap_const_logic_1;
    } else {
        data_local_3_ce0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_3_d0() {
    data_local_3_d0 = data_dram_addr_read_reg_340.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_3_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,3,3>(tmp_reg_331_pp0_iter1_reg.read(), ap_const_lv3_3))) {
        data_local_3_we0 = ap_const_logic_1;
    } else {
        data_local_3_we0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_4_address0() {
    data_local_4_address0 =  (sc_lv<8>) (newIndex8_fu_290_p1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_4_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        data_local_4_ce0 = ap_const_logic_1;
    } else {
        data_local_4_ce0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_4_d0() {
    data_local_4_d0 = data_dram_addr_read_reg_340.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_4_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,3,3>(tmp_reg_331_pp0_iter1_reg.read(), ap_const_lv3_4))) {
        data_local_4_we0 = ap_const_logic_1;
    } else {
        data_local_4_we0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_5_address0() {
    data_local_5_address0 =  (sc_lv<8>) (newIndex8_fu_290_p1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_5_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        data_local_5_ce0 = ap_const_logic_1;
    } else {
        data_local_5_ce0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_5_d0() {
    data_local_5_d0 = data_dram_addr_read_reg_340.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_5_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,3,3>(tmp_reg_331_pp0_iter1_reg.read(), ap_const_lv3_5))) {
        data_local_5_we0 = ap_const_logic_1;
    } else {
        data_local_5_we0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_6_address0() {
    data_local_6_address0 =  (sc_lv<8>) (newIndex8_fu_290_p1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_6_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        data_local_6_ce0 = ap_const_logic_1;
    } else {
        data_local_6_ce0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_6_d0() {
    data_local_6_d0 = data_dram_addr_read_reg_340.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_6_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,3,3>(tmp_reg_331_pp0_iter1_reg.read(), ap_const_lv3_6))) {
        data_local_6_we0 = ap_const_logic_1;
    } else {
        data_local_6_we0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_7_address0() {
    data_local_7_address0 =  (sc_lv<8>) (newIndex8_fu_290_p1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_7_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1))) {
        data_local_7_ce0 = ap_const_logic_1;
    } else {
        data_local_7_ce0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_7_d0() {
    data_local_7_d0 = data_dram_addr_read_reg_340.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_data_local_7_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
         esl_seteq<1,3,3>(tmp_reg_331_pp0_iter1_reg.read(), ap_const_lv3_7))) {
        data_local_7_we0 = ap_const_logic_1;
    } else {
        data_local_7_we0 = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_exitcond_fu_265_p2() {
    exitcond_fu_265_p2 = (!i_reg_225.read().is_01() || !num_elem.read().is_01())? sc_lv<1>(): sc_lv<1>(i_reg_225.read() == num_elem.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_i_1_fu_270_p2() {
    i_1_fu_270_p2 = (!i_reg_225.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_reg_225.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARADDR() {
    m_axi_data_dram_ARADDR = sum2_cast_fu_250_p1.read();
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARBURST() {
    m_axi_data_dram_ARBURST = ap_const_lv2_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARCACHE() {
    m_axi_data_dram_ARCACHE = ap_const_lv4_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARID() {
    m_axi_data_dram_ARID = ap_const_lv1_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARLEN() {
    m_axi_data_dram_ARLEN = esl_zext<32,11>(num_elem.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARLOCK() {
    m_axi_data_dram_ARLOCK = ap_const_lv2_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARPROT() {
    m_axi_data_dram_ARPROT = ap_const_lv3_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARQOS() {
    m_axi_data_dram_ARQOS = ap_const_lv4_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARREGION() {
    m_axi_data_dram_ARREGION = ap_const_lv4_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARSIZE() {
    m_axi_data_dram_ARSIZE = ap_const_lv3_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARUSER() {
    m_axi_data_dram_ARUSER = ap_const_lv1_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_m_axi_data_dram_ARREADY.read()))) {
        m_axi_data_dram_ARVALID = ap_const_logic_1;
    } else {
        m_axi_data_dram_ARVALID = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWADDR() {
    m_axi_data_dram_AWADDR = ap_const_lv64_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWBURST() {
    m_axi_data_dram_AWBURST = ap_const_lv2_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWCACHE() {
    m_axi_data_dram_AWCACHE = ap_const_lv4_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWID() {
    m_axi_data_dram_AWID = ap_const_lv1_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWLEN() {
    m_axi_data_dram_AWLEN = ap_const_lv32_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWLOCK() {
    m_axi_data_dram_AWLOCK = ap_const_lv2_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWPROT() {
    m_axi_data_dram_AWPROT = ap_const_lv3_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWQOS() {
    m_axi_data_dram_AWQOS = ap_const_lv4_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWREGION() {
    m_axi_data_dram_AWREGION = ap_const_lv4_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWSIZE() {
    m_axi_data_dram_AWSIZE = ap_const_lv3_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWUSER() {
    m_axi_data_dram_AWUSER = ap_const_lv1_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_AWVALID() {
    m_axi_data_dram_AWVALID = ap_const_logic_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_BREADY() {
    m_axi_data_dram_BREADY = ap_const_logic_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        m_axi_data_dram_RREADY = ap_const_logic_1;
    } else {
        m_axi_data_dram_RREADY = ap_const_logic_0;
    }
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_WDATA() {
    m_axi_data_dram_WDATA = ap_const_lv64_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_WID() {
    m_axi_data_dram_WID = ap_const_lv1_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_WLAST() {
    m_axi_data_dram_WLAST = ap_const_logic_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_WSTRB() {
    m_axi_data_dram_WSTRB = ap_const_lv8_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_WUSER() {
    m_axi_data_dram_WUSER = ap_const_lv1_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_m_axi_data_dram_WVALID() {
    m_axi_data_dram_WVALID = ap_const_logic_0;
}

void digitrec_kernel_load_unsigned_long_s::thread_newIndex8_fu_290_p1() {
    newIndex8_fu_290_p1 = esl_zext<64,8>(newIndex_reg_335_pp0_iter1_reg.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_sum2_cast_fu_250_p1() {
    sum2_cast_fu_250_p1 = esl_zext<64,62>(sum2_reg_301.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_sum2_fu_244_p2() {
    sum2_fu_244_p2 = (!data_dram_offset_cast_fu_240_p1.read().is_01() || !tmp_23_cast_fu_236_p1.read().is_01())? sc_lv<62>(): (sc_biguint<62>(data_dram_offset_cast_fu_240_p1.read()) + sc_biguint<62>(tmp_23_cast_fu_236_p1.read()));
}

void digitrec_kernel_load_unsigned_long_s::thread_tmp_23_cast_fu_236_p1() {
    tmp_23_cast_fu_236_p1 = esl_zext<62,15>(data_dram_offset1.read());
}

void digitrec_kernel_load_unsigned_long_s::thread_tmp_fu_276_p1() {
    tmp_fu_276_p1 = i_reg_225.read().range(3-1, 0);
}

void digitrec_kernel_load_unsigned_long_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_m_axi_data_dram_ARREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 256 : 
            if ((!(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_fu_265_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(exitcond_fu_265_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXX";
            break;
    }
}

}

